#!/bin/sh -f
nm="$1"

valgrind=${valgrind:-/opt/SciDAC/fen64/valgrind-3.2.3/bin/valgrind}

builtin echo -n $nm ''

[ -d valgrind.test ] || mkdir valgrind.test
[ -f valgrind.test/random-gauge.nersc ] || ln random-gauge.nersc valgrind.test/
[ -f valgrind.test/random-gauge.qio ] || ln random-gauge.qio valgrind.test/
cd valgrind.test

$valgrind \
  --tool=memcheck \
  --leak-check=yes \
  --log-file=$nm.valgrind \
  --time-stamp=yes \
  --leak-check=full \
  --show-reachable=yes \
  --dsymutil=yes \
 ../../qlua \
  ../$nm \
  > $nm.output \
  2> $nm.error
echo $?
