#!/bin/sh
PACKTOP=$HOME/Local/packages/macosx-hql

#TARGET=`(cd ..; pwd)`/install
TARGET=$HOME/Local/packages/qlua-working
## for all colors. 

CC='mpicc -m64 -std=c99' \
CFLAGS='-Wall -DQDP_Nc=3' \
COPTS='-O2' \
./configure                                   \
   --with-qdp=$PACKTOP/qdp                    \
   --with-lua=$PACKTOP/lua                    \
   --with-gsl=$PACKTOP/gsl                    \
   --with-lhpc-aff=$PACKTOP/aff               \
   --with-hdf5=$HOME/Local/packages/hdf5-1.8.10-patch1 \
   --with-clover=$PACKTOP/clover              \
   --with-mdwf=$PACKTOP/mdwf                  \
   --with-hql=$HOME/Local/packages/hql-dummy \
   --with-extras                              \
   --prefix=$TARGET                           \
   $*
