#!/bin/sh
PACKTOP=/Users/avp/Local/packages/qlua-devel

#TARGET=`(cd ..; pwd)`/install
TARGET=$PACKTOP/qlua-working
## for all colors. 

CC="gcc -g -std=c99 -DQDP_Nc=3"               \
./configure                                   \
   --with-qdp=$PACKTOP/qdp                    \
   --with-lua=$PACKTOP/lua                    \
   --with-gsl=$PACKTOP/gsl                    \
   --with-lhpc-aff=$PACKTOP/aff               \
   --with-clover=$PACKTOP/clover              \
   --with-mdwf=$PACKTOP/mdwf                  \
   --with-extras                              \
   --prefix=$TARGET                           \
   --without-nc=any                           \
   --with-nc=3                                \
   $*
