#!/bin/sh
PACKTOP=$HOME/Local/packages/macosx-working
DEVTOP=$HOME/Local/packages
Nc=3
# noNc=3

#TARGET=`(cd ..; pwd)`/install
TARGET=$DEVTOP/qlua-working

# XXX Nc specific clover installation location

# for real GCC
WOPTS='-Wno-unused-but-set-variable -Wno-unused-local-typedefs'
# for clang mascarading as gcc
# WOPTS='-Wunused-const-variable'

ARPACK_LIBS="-L$PACKTOP/arpack/lib -lparpack -larpack"
LAPACK_LIBS="-L$PACKTOP/lapack/lib -llapack"

#LD='mpicc -m64 -fno-underscoring' \
#

CC='mpicc -fopenmp -m64 -std=c99' \
LD='mpif77 -fopenmp -m64 -fno-underscoring' \
CFLAGS="-Wall $WOPTS -DQDP_Nc=$Nc -g" \
COPTS='-g' \
LIBS='-lz' \
./configure                                                \
   --prefix=$TARGET                                        \
   --with-qdp=$PACKTOP/qdp                                 \
   --with-lua=$PACKTOP/lua                                 \
   --with-gsl=$PACKTOP/gsl                                 \
   --with-arpack="$ARPACK_LIBS $LAPACK_LIBS"               \
   --with-hdf5=$PACKTOP/hdf5                               \
   --with-qopqdp=$PACKTOP/qopqdp                           \
   --with-clover=$DEVTOP/clover-working                    \
   --clover-nc=$Nc                                         \
   --without-nc=N                                          \
   --with-nc=3                                             \
   --without-nc=2                                          \
   $*

#   --with-mdwf=$DEVTOP/mdwf-working                        \
#   --with-mdwf=$PACKTOP/mdwf                               \
#   --with-arpack="$ARPACK_LIBS $LAPACK_LIBS"               \
#   --without-nc=$noNc                                      \
#   --without-nc=N                                          \
#   --with-nc=N                                             \
#   --with-nc=3                                             \
