#!/bin/sh
CC='gcc -m64' \
./configure \
   --with-lua=/opt/SciDAC/fen64/lua-5.1.4 \
   --with-qdp=/opt/SciDAC/fen64/qdp-1.8.1 \
   --with-lhpc-aff=/opt/SciDAC/fen64/lhpc-aff-2.1.0rc1 \
   --with-clover=/opt/SciDAC/fen64/clover-1.0.2

#   --with-clover=/Users/avp/Local/test/clover-1.0.1 \
#   --with-mdwf=/Users/avp/Local/test/mdwf-1.1.4
