#!/bin/sh
COPTS='-Wall -O2' \
LIBS='-lm' \
CC='xgcc' \
AR='xar' \
RANLIB='xranlib' \
./configure \
   --prefix=/opt/SciDAC/bgl/qlua-0.9.3 \
   --with-lua=/opt/SciDAC/bgl/lua-5.1.4 \
   --with-qdp=/opt/SciDAC/bgl/qdp-1.8.1 \
   --with-lhpc-aff=/opt/SciDAC/bgl/lhpc-aff-2.1.0rc1 \
   --with-clover=/opt/SciDAC/bgl/clover-1.0.3

#   --with-mdwf=/Users/avp/Local/test/mdwf-1.1.4
