#!/bin/sh

extract_file() {
  if [ -f "$1" ] ; then
    incs=`grep '#include.*DEPS' $1 \
          | sed -e 's/^.* "//;s/".*$//'`
    o=`basename $1 .c`
    for i in $incs ; do
      if [ -f "sources/$i" ] ; then
         echo "$o.o: sources/$i"
      elif [ -f "extras/$i" ] ; then
         echo "$o.o: extras/$i"
      fi
    done
  fi
}

for f in sources/*.c extras/*.c ; do
  extract_file $f
done | sort