#!/bin/sh
PACKTOP=/Users/avp/Local/packages

TARGET=`(cd ..; pwd)`/install

./configure \
   --prefix=$TARGET \
   --with-extras \
   --with-lua=$PACKTOP/lua-5.1.4 \
   --with-qdp=$PACKTOP/qdp-1.8.1 \
   --with-lhpc-aff=$PACKTOP/lhpc-aff-2.1.0 \
   --with-clover=$PACKTOP/clover-1.1.0 \
   --with-extras

# \
#   --with-mdwf=$PACKTOP/mdwf-1.2.0-rc2
