#!/bin/sh
PACKTOP=/Users/avp/Local/packages/current

#TARGET=`(cd ..; pwd)`/install
TARGET=/Users/avp/Local/package/qlua-0.22.00-w0

CC="gcc -g -std=c99" \
LD="gcc -g" \
./configure \
   --prefix=$TARGET \
   --with-extras \
   --with-lua=$PACKTOP/lua \
   --with-qdp=$PACKTOP/qdp \
   --with-lhpc-aff=$PACKTOP/aff \
   --with-clover=$PACKTOP/clover \
   --with-gsl=$PACKTOP/gsl \
   --with-mdwf=$PACKTOP/mdwf \
   --without-nc=any \
   --with-nc=3 \
   --with-extras

#   --with-clover=$PACKTOP/clover-1.1.0 \
# \
#   --with-mdwf=$PACKTOP/mdwf-1.2.0-rc2
